### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kstrohmayer** [semify-eda/wfg-API#10]
The following steps need to the done for the Python API documentation:
  - Extract the documentation from the Python code (Tool?)
  - Generate a markdown page and add it to the https://github.com/semify-eda/wfg-doc/docs
  - Should be part of the already existing building process 
  - Website under: https://doc.semify-eda.com/

**Comment by adam-hrvth** [comment]
The API documentation can now be accessed from https://doc.semify-eda.com/
I ran into some issues when I tried to host a Sphinx documentation from a submodule on GitHub pages and couldn't find a nice solution for it. Right now I have a workaround, where I host the Sphinx documentation on a separate GitHub pages for the API, and link it to the wfg-docs. As long as everything is maintained, this would work, but I'll ask for some help on the official Sphinx GitHub page to come up with a better solution

**Comment by kstrohmayer** [comment]
Can we add some examples to the docu like on [PyPi](<https://pypi.org/project/SmartWaveAPI/>).

**Comment by adam-hrvth** [comment]
> Can we add some examples to the docu like on [PyPi](https://pypi.org/project/SmartWaveAPI/).

I will look into it.
