### ISSUE TITLE
GPIO input level read incorrectly

### ISSUE THREAD

**Issue by adam-hrvth** [semify-eda/wfg-API#18]
During some GPIO functionality testing, it was discovered that the `inputLevel` function does not accurately read the voltage applied to the pin, but rather returns the level it was set to. For instance, if a pin level is set to `1` but is connected to `GND` to test short detection, the `inputLevel` function incorrectly returns a `1` instead of `0`. Similarly, if set to `0` and connected to `VCC`, it returns a `0` instead of `1`.

**Comment by precap** [comment]
As each pin has a 22R output protection resistor, shorting pins actually is not a short, its a 44R wire.
You will need to measure with one driver pin and one follower that has only the pullup enabled.
